# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='description',
            field=models.TextField(help_text='Describe about your education and where you want to study.'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='email',
            field=models.EmailField(help_text='Your Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='name',
            field=models.CharField(help_text='Your Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='phone_number',
            field=models.CharField(help_text='Phone number', max_length=12),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='school',
            field=models.CharField(help_text='Your previous school', max_length=50),
        ),
    ]
