# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20160803_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 3, 9, 11, 31, 937273)),
            preserve_default=False,
        ),
    ]
